name: proyectproducts
description: "A combined Flutter project."
version: 1.0.0+2

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  table_calendar: ^3.0.7
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  uuid: ^4.5.1
  flutter_bloc: ^8.1.3
  google_ml_kit: ^0.18.0
  image_picker: ^1.0.1  
  camera: ^0.10.5+2
  path: ^1.8.3
  path_provider: ^2.0.15
  google_mlkit_commons: ^0.7.1
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/1.webp
    - assets/images/2.jpg
    - assets/images/3.jpeg
    - assets/images/4.jpeg
    - assets/images/push-up-animation.json
    - assets/images/background_image.jpg
