name: proyectproducts
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.0.3 
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  cloud_firestore: ^5.0.0
  table_calendar: ^3.0.6  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
